#! /usr/bin/env python

import os
import subprocess

source = "/project01/ndcms/cmoore24"
destination = "filelists"

datasets = {
    "Hgg": "signal/hgg",
    "Hbb": "signal/hbb",
    "QCD_Pt_300to470": "qcd/300to470",
    "QCD_Pt_470to600": "qcd/470to600",
    "QCD_Pt_600to800": "qcd/600to800",
    "QCD_Pt_800to1000": "qcd/800to1000",
    "QCD_Pt_1000to1400": "qcd/1000to1400",
    "QCD_Pt_1400to1800": "qcd/1400to1800",
    "QCD_Pt_1800to2400": "qcd/1800to2400",
    "QCD_Pt_2400to3200": "qcd/2400to3200",
    "QCD_Pt_3200toInf": "qcd/3200toInf",
}

for label, path in datasets.items():
    with open(os.path.join(destination, f"{label}"), "w") as f:
        subprocess.run(["find", path, "-name", "*.root"],  cwd=source, stdout=f)

